# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: KZZ
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    # GitHub Actions 使用的是UTC时间，比北京时间慢八个小时
    # 例：如需调整为14:30， 将45改为30即可
    # 设置仅周内运行，将最后一个'*'改为'1-5'
    - cron: '0 14 * * *'

jobs:
  KZZ:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz datetime configparser
    - name: Run KZZ script
      run: |
        sed -i "s/ServerChanKey/${{ secrets.ServerChanKey }}/g" kzz.py
        sed -i "s/KzzInfoUrl/${{ secrets.KzzInfoUrl }}/g" kzz.py
        sed -i "s/KzzListUrl/${{ secrets.KzzListUrl }}/g" kzz.py
        python ./kzz.py >> /dev/null
